/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard/notifications'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as TrackIndexRouteImport } from './routes/track/index'
import { Route as TrackTrackingNumberRouteImport } from './routes/track/$trackingNumber'
import { Route as DashboardOrganizationsIndexRouteImport } from './routes/dashboard/organizations/index'
import { Route as DashboardOrganizationsIdRouteImport } from './routes/dashboard/organizations/$id'
import { Route as DashboardShipmentsIndexRouteImport } from './routes/dashboard/shipments/index'
import { Route as DashboardShipmentsShipmentIdRouteImport } from './routes/dashboard/shipments/$shipmentId'
import { Route as DashboardUsersIndexRouteImport } from './routes/dashboard/users/index'
import { Route as DashboardUsersIdRouteImport } from './routes/dashboard/users/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackIndexRoute = TrackIndexRouteImport.update({
  id: '/track/',
  path: '/track/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackTrackingNumberRoute = TrackTrackingNumberRouteImport.update({
  id: '/track/$trackingNumber',
  path: '/track/$trackingNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrganizationsIndexRoute =
  DashboardOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardOrganizationsIdRoute =
  DashboardOrganizationsIdRouteImport.update({
    id: '/organizations/$id',
    path: '/organizations/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardShipmentsIndexRoute = DashboardShipmentsIndexRouteImport.update({
  id: '/shipments/',
  path: '/shipments/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardShipmentsShipmentIdRoute =
  DashboardShipmentsShipmentIdRouteImport.update({
    id: '/shipments/$shipmentId',
    path: '/shipments/$shipmentId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUsersIdRoute = DashboardUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/invite/$token': typeof InviteTokenRoute
  '/track/$trackingNumber': typeof TrackTrackingNumberRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/track/': typeof TrackIndexRoute
  '/dashboard/organizations/$id': typeof DashboardOrganizationsIdRoute
  '/dashboard/shipments/$shipmentId': typeof DashboardShipmentsShipmentIdRoute
  '/dashboard/users/$id': typeof DashboardUsersIdRoute
  '/dashboard/organizations/': typeof DashboardOrganizationsIndexRoute
  '/dashboard/shipments/': typeof DashboardShipmentsIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/invite/$token': typeof InviteTokenRoute
  '/track/$trackingNumber': typeof TrackTrackingNumberRoute
  '/dashboard': typeof DashboardIndexRoute
  '/track': typeof TrackIndexRoute
  '/dashboard/organizations/$id': typeof DashboardOrganizationsIdRoute
  '/dashboard/shipments/$shipmentId': typeof DashboardShipmentsShipmentIdRoute
  '/dashboard/users/$id': typeof DashboardUsersIdRoute
  '/dashboard/organizations': typeof DashboardOrganizationsIndexRoute
  '/dashboard/shipments': typeof DashboardShipmentsIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/invite/$token': typeof InviteTokenRoute
  '/track/$trackingNumber': typeof TrackTrackingNumberRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/track/': typeof TrackIndexRoute
  '/dashboard/organizations/$id': typeof DashboardOrganizationsIdRoute
  '/dashboard/shipments/$shipmentId': typeof DashboardShipmentsShipmentIdRoute
  '/dashboard/users/$id': typeof DashboardUsersIdRoute
  '/dashboard/organizations/': typeof DashboardOrganizationsIndexRoute
  '/dashboard/shipments/': typeof DashboardShipmentsIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/invite/$token'
    | '/track/$trackingNumber'
    | '/dashboard/'
    | '/track/'
    | '/dashboard/organizations/$id'
    | '/dashboard/shipments/$shipmentId'
    | '/dashboard/users/$id'
    | '/dashboard/organizations/'
    | '/dashboard/shipments/'
    | '/dashboard/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/invite/$token'
    | '/track/$trackingNumber'
    | '/dashboard'
    | '/track'
    | '/dashboard/organizations/$id'
    | '/dashboard/shipments/$shipmentId'
    | '/dashboard/users/$id'
    | '/dashboard/organizations'
    | '/dashboard/shipments'
    | '/dashboard/users'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/invite/$token'
    | '/track/$trackingNumber'
    | '/dashboard/'
    | '/track/'
    | '/dashboard/organizations/$id'
    | '/dashboard/shipments/$shipmentId'
    | '/dashboard/users/$id'
    | '/dashboard/organizations/'
    | '/dashboard/shipments/'
    | '/dashboard/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  InviteTokenRoute: typeof InviteTokenRoute
  TrackTrackingNumberRoute: typeof TrackTrackingNumberRoute
  TrackIndexRoute: typeof TrackIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/': {
      id: '/track/'
      path: '/track'
      fullPath: '/track/'
      preLoaderRoute: typeof TrackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$trackingNumber': {
      id: '/track/$trackingNumber'
      path: '/track/$trackingNumber'
      fullPath: '/track/$trackingNumber'
      preLoaderRoute: typeof TrackTrackingNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/organizations/': {
      id: '/dashboard/organizations/'
      path: '/organizations'
      fullPath: '/dashboard/organizations/'
      preLoaderRoute: typeof DashboardOrganizationsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/organizations/$id': {
      id: '/dashboard/organizations/$id'
      path: '/organizations/$id'
      fullPath: '/dashboard/organizations/$id'
      preLoaderRoute: typeof DashboardOrganizationsIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/shipments/': {
      id: '/dashboard/shipments/'
      path: '/shipments'
      fullPath: '/dashboard/shipments/'
      preLoaderRoute: typeof DashboardShipmentsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/shipments/$shipmentId': {
      id: '/dashboard/shipments/$shipmentId'
      path: '/shipments/$shipmentId'
      fullPath: '/dashboard/shipments/$shipmentId'
      preLoaderRoute: typeof DashboardShipmentsShipmentIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/users'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/users/$id': {
      id: '/dashboard/users/$id'
      path: '/users/$id'
      fullPath: '/dashboard/users/$id'
      preLoaderRoute: typeof DashboardUsersIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardOrganizationsIdRoute: typeof DashboardOrganizationsIdRoute
  DashboardShipmentsShipmentIdRoute: typeof DashboardShipmentsShipmentIdRoute
  DashboardUsersIdRoute: typeof DashboardUsersIdRoute
  DashboardOrganizationsIndexRoute: typeof DashboardOrganizationsIndexRoute
  DashboardShipmentsIndexRoute: typeof DashboardShipmentsIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardOrganizationsIdRoute: DashboardOrganizationsIdRoute,
  DashboardShipmentsShipmentIdRoute: DashboardShipmentsShipmentIdRoute,
  DashboardUsersIdRoute: DashboardUsersIdRoute,
  DashboardOrganizationsIndexRoute: DashboardOrganizationsIndexRoute,
  DashboardShipmentsIndexRoute: DashboardShipmentsIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  InviteTokenRoute: InviteTokenRoute,
  TrackTrackingNumberRoute: TrackTrackingNumberRoute,
  TrackIndexRoute: TrackIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
